### PR TITLE
Add task to cleanup issues periodically

### PR DESCRIPTION
**Pull request by paveldedik**
- remove issues of deleted kind
- remove issues older than configured number of hours (default 2)
- related issue: https://github.com/kiwicom/the-zoo/issues/19

### CODE REVIEW

**Comment by JanBednarik** [comment]
@aexvir We were discussing this solution as one of options with Pavel. We decided that separate cleanup task will be better.

Some reasons are in issue #19. Maybe most important reason is that solution you suggested will delete also issues for checks which temporarily fails and yields no results (like when check relies on 3rd party API which is temporarily not available). It's better to keep them with old last check date than delete them.

If you want, we can talk about it.

**Comment by aexvir** [comment]
As I see it there is no big deal of having the checks deleted if they are not returning anything. The dev of the check can (and probably should) react if the 3rd party api responds or not and still return something. What could be discussed here is the need of some indication for an error status, which seems like something we'll eventually need.

If a check is not working correctly there is not a big value on having it either way. The responsible of the check working fine and making sure that stuff is returned when it's needed and not returned when is not it's the developer of the check itself.

The periodic task is also not solving this issue either. If nothing is returned the Issue will not be updated and it will be deleted either way, with a delay of two hours, but still delayed. If you really think that delay is important it can be easily added to the solution I propose as well.

On the contrary, having a periodic task deleting all the checks that weren't updated in the last two hours can carry bigger problems, like for some reason there is an error scheduling the pull tasks but having the cleanup tasks being scheduled correctly, in that case we could end up with all our issues removed, and the developer of the checks wouldn't be responsible for this error, as it's not something he can control.

And overall it makes way more sense to do this in the only place where the status of the issues is managed, which is the runner.

**Comment by JanBednarik** [comment]
Let's talk about it on Monday, it will be more effective.

**Comment by underyx** [comment]
> for some reason there is an error scheduling the pull tasks but having the cleanup tasks being scheduled correctly, in that case we could end up with all our issues removed, and the developer of the checks wouldn't be responsible for this error, as it's not something he can control

This is a dealbreaker indeed. I think we should go with Alex's suggestion.

Consider also adding a `gone` status and keeping those around for 7 days or so, and then cleaning them up. The app can then display them in the report: "this issue is gone, will be deleted soon" — but users might get confused by this when the zoo maintainers remove a check.

I scheduled a meeting for Monday 10am where the four of us will design this. @JanBednarik @paveldedik please prepare by thinking of some solution for the problem I quoted.

**Pull request closed without merging**
